workflows:
  build_ios_release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
