scripts:
  - name: Clean and reset
    script: |
      flutter clean
      rm -f pubspec.lock
      flutter pub cache repair
  - name: Install dependencies
    script: flutter pub get
  - name: Build iOS release
    script: flutter build ios --release --no-codesign
