workflows:
  ios-release:
    name: Build iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
