workflows:
  ios-build:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and reset
        script: |
          flutter clean
          rm pubspec.lock
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS release
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa

