name: thankinh_pex
description: Ứng dụng theo dõi thay huyết tương (PEX) gửi y lệnh qua WiFi
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_signature_pad: ^3.0.0
  shared_preferences: ^2.2.0
  nearby_connections: ^3.1.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
