name: thankinh_pex
description: Ứng dụng theo dõi điều trị thay huyết tương (PEX)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  signature: ^5.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

